services:
  - type: web
    name: prithish-ray-portfolio
    env: static
    buildCommand: pip install -r requirements.txt && python build.py
    staticPublishPath: _site
    routes:
      - type: rewrite
        source: /404
        destination: /404.html
